hash-format = "sha256"

[[files]]
file = "README.md"
hash = "811f4c40c6ae0437e14cf0ccf619b81aa9e51c16f141cf0ba9ace8c3c4fb019f"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "9bfc325933e09fd56bb3fec6d984d9d828b000dadd6a22339e9721a3359e6afe"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ac3444154dfbd155eaa377eb00fdab860d7436249f73a9ef29acf7d4fb3c38d7"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "eb586237c139da61053ce14ea9a8d6cb3124e1731db22963ae79192b59b4c063"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "611dd38f46108493b1d0b63cb3580d522b42d43e6680ab07de74f51224e18a10"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ab72b447ed976a93ce1124524295ab8a469438b741bdc224aefb1ad7d881e0cf"
metafile = true

[[files]]
file = "mods/auto-clicker.pw.toml"
hash = "4c54284e5070fa0de2e0d606c719e0db918d7553a7e2ebf94c495e6cee567768"
metafile = true

[[files]]
file = "mods/auto-lectern.pw.toml"
hash = "4e9d3d6293bbc4d77eeb1959f2e30592777f2f9f3103672725526b7e47a9898f"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "c0921bb5170f07b05acc2dcd2df5b61c08e0b92ba859285993dd4a3feabde116"
metafile = true

[[files]]
file = "mods/beetooltip.pw.toml"
hash = "15c048f5116a6e0df27a05696945eb97b2017052c1b5d023e37ef8d98cf5a7ed"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "5309c13521cd3781aed216c44ab66f87a08eaf10d891fdce05bb7e045f59ea8c"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "d69de5e020139a28ca7b7256ad6f1d598ba09a1b6b051e326fc28261cf4f12b7"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7c801232a6e7b3930c6c6f47f2c4cd77a539f28bc41e6d54e1710c2736d8a46f"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "579bfabe383e954cf7aa119ca680211db0c92e1edfb1a08d059cbd1f8aac85af"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "c455d55e736f90f6a09701594dee2342e91c77b7f230f0ff73090d7ead339629"
metafile = true

[[files]]
file = "mods/brb.pw.toml"
hash = "04be795fbd9b7977281911ae0526de20340e07214562269a47ef991b1c863cd5"
metafile = true

[[files]]
file = "mods/build-guide.pw.toml"
hash = "bcf12705158f03576d370a06b0fcd2c796d9d110f686548cdcb01ce4b276bc16"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a4fd2e20e1a2444c6892e9f14d94b1b8802a8a4954f9e3e49045aac9b9074f23"
metafile = true

[[files]]
file = "mods/cardinalboats.pw.toml"
hash = "e1939f69f1b60fa7e6760597acdfb4410a9ec8d9c1f21638b5ac93e30f5db766"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "73b49e93bdc437c2cd86133b5cfb0a04f80264f785ee660ce002bb24e14286c1"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2170852aa2753da85a17e144c08e86c0edfe1d6e0a8138d686ac5f8553b37c35"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "3992f39495d3c9beb3db62f43dd45f9b383471ff4c5e274bcce146090756e672"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "249d865e83cf0f5e516a98b9f71b99b9568b2be69e5ecc48ae31cc5e03bd1b3b"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "9831c303787202296c85b548c9139a5f2c67471f22bad772a5da55b5859036e3"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "4674f4ffc35811e5f1bdf2cb4fa88021b9ed129e06efee3c20c9b4b1714dcd01"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "cfc2c53b0d3cee953b423fe9abf210d87281d5bf774dab20cf03abe6224a9883"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "1d87db84f4f4180aa5ddbd35085d3ee780db9ebc75cc2adf5331249f424102f4"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "66b27fa4b5af9a926ddfdbaa91b2599640f7ba6b7b7237cae3a9bb6ceb4c2e91"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "c03d77f40b53a229112df4cd4a83468ea6eee119549c79accfadb508cf9fb989"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "97ca0b01ac6888486402018e7c95ec3b219a89c3338a416fd25418def5f51fa1"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "7c4410424962acf607a4b2ff1e522553bdf742d6025ad077772d4d9ec7ef5e50"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "c76fb1dc72892fcd61ff8c7149d56979a4f7ea23e97d82558ccc9920aab0b006"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "d29e52714402fe3f95bc68b8b060da85cda3e575247cdc6f7d00c2fcfe270838"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "9099b858e94f6f81db890c7d46f85601dee71ba33fb7ae19773b8da2ce8c3834"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "2e1ed52274d3c3a5b2aa578b145a83a6095c177da7d9e5fd6379d3eaccf5ca18"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "510a734d5276b5bc094162b4fdcf167f637b54915e31e20d14ecc87b79778541"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9acaedce53ce2f14333653a90c57d684f5cd740c29411686054878638577be1e"
metafile = true

[[files]]
file = "mods/fast-trading.pw.toml"
hash = "84b04b55bec7f7d8591867afd466a64e1651e7577716b6d2e061f58af2227aac"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "babe89b61b069779a4532a3c5c66881b0422337eec61cedfed3fc873dc52445a"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "3b6749a8f0a53d7e6c748651f2f58a297f20f2a7b72b083d63b81295559f626a"
metafile = true

[[files]]
file = "mods/gui-followers.pw.toml"
hash = "46445ed84c96e4a42c2e520e57c2e8e56b186928ba7f92eab1cdfae8187dec5d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "8aa6b67c8edeebbc7fb923449563c17d4c01df00d45ca7441b988c093b30c846"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "49e7fd585c233da81e0825d1679028c7e0bc1eb74dafa98f25cab88437f53ed1"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "a36870bfbbd57ea241255c6573a4d129509f5e50dbdcaf12d3a78c57f864bbde"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "0adcdcc6092f8709a396ef315823c6a5db0bb3b35307d7f1c16f3e932c93b079"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "5c372fe797637e7e33c7af4b9da5f50a550d9ddb6566b80149edf9e63c2e2a3c"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "012ec092803f672ce6f884dfa400497e2e4e8063a3af4e3cdee911dea10ab2c9"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "cc491adadeb1c1645f1f65073d9543eea1914425a17ad8338e61a4de05c00471"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4ee72fa3b6d91ccec6ec3420396db368dc5097350ee2bb909af3a65f0446c9d5"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "80ec786a43f9a126979ef102ebf1ea3e92d86ec8d3226d35659b7abab525c017"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "de5cf3ebdd9c62fd60ad8771027cfdb050b88b7dfd009247188dd9e9b4ebc631"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "e83aebbd22e7a4e92844b7d83a9c68cc1477bc301b1ab60744870f11db0d5886"
metafile = true

[[files]]
file = "mods/map-tooltip.pw.toml"
hash = "93bf5e760cb6e64e70a01b4151a920d25f18f6bca3a062d6836c11a8611743b5"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7c6264919760fa6e9d35337dbe9ce49e527c8539dddb2f7fcd2161463de1eea2"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "87f32c96066eb295c234effb49f6f5cbd5956316a3a750a3989cfb645b3fd397"
metafile = true

[[files]]
file = "mods/music-notification.pw.toml"
hash = "888e1dbb79478243a31a0fbcd875a4f8454c4becd076416b1267ff5be9e8aed6"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "9c4a21536e1743737e5916d2ecaa2b16abaac1a6ea19df902cb6ba943c7b35d3"
metafile = true

[[files]]
file = "mods/notifmod.pw.toml"
hash = "67e1019de7c1ef06c11eb2bdcf34bd11f1a655bfa811914971b44bd1d073f30c"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "4bf4725c5be913048b3b0c6dfcdc1a98ac99baeaeda0d34dde411ab3972fb997"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "9db90dbca5f74ae9eef6d3bfef116b2c93eb52e1151df241e35b358754594e95"
metafile = true

[[files]]
file = "mods/persistent-inventory-search.pw.toml"
hash = "e55f55014a027f7ae88362e7294c62040edc627ffa7858a98335ded3e2902870"
metafile = true

[[files]]
file = "mods/pocketwatch.pw.toml"
hash = "7c7da6b96ea84ce02933fee08c2b00592a62a8cc81e2fccce7204cdb2808640a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2057649daa10fcdc620dfd60eb0caee54b9ff80c80979564873b422fa94e2ced"
metafile = true

[[files]]
file = "mods/ridehud.pw.toml"
hash = "bf9f7fc49e21a0f427ad6819162cac95f960d8ac127b90937ce97eb660358366"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "f632c6f98de8644ad2fa0153ab1211bd9f2751fe84620b894ab5f6f558efaae4"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "d50d177305c0923e5b71f517fb570754a31e6b53505085293042b951a3acbe60"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "efe87e84d86e32cec8cfbeac1995d1891ec3d6596d3ef1eefcb43b96113cc441"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "fa41e05d17ae825fe60001763b2160c15b3998fb0352fce0e70af67172afb262"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d6e22a99e0b73a91cfd528aed964bc8acb001188e76804406b998a19f645fbe1"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "06aa6eb22d7002de4f01e4b03469118fdd2cf824fe203e785bfe22edf889c651"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "6533e7eaad68cad764272e5c4857a075ceb8a149546fec0d16179ba2a1a49fee"
metafile = true

[[files]]
file = "mods/vanillaconfig.pw.toml"
hash = "97f02d1e437693a8135cc701df1447d6ab74d893bc12315e10d79f2dac0d47cd"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "6cb2a4cd4eb40eaf19bbb54a6d8fa23643470147e86e19fe04b820e170998ed3"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "4fd0d40dfda1403970491c7d33a748477f50613fd138b0c5c1fcd87c5ed6f804"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f29d86ce2b0468bb1b6e576145969e7c9d2cddd0d4c02f07bfa07c98315c13e1"
metafile = true

[[files]]
file = "resourcepacks/EvenBetterEnchants_v2_r1.zip"
hash = "bf3879bfe3607936248a070037c730082a46556ef2cdfb285e05ac93a88665ea"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x.zip"
hash = "ea8ed4c8ca8266ce2e61de35f51db9effea252ba56c8681e25471c1e31c22f90"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x_BushyLeaves.zip"
hash = "36299e2ef6a16ff750e0f57ff8a27c79ca65a6200528756bfdc4d3bf835142c3"

[[files]]
file = "resourcepacks/deep-origins-overlaysÂ§8_1-2-2_1-17_1-21.zip"
hash = "17af52a6b1d484fde2b240fb3d7445bbd9dce0a7840ed1559a34fe161d592487"

[[files]]
file = "shaderpacks/BSL_v8.2.09.zip"
hash = "b9f9e70c83f04830007ec06e6d7c3e0fafe90c6af53355e4248ab0a59ca1cf48"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.2.1.zip"
hash = "3eeefb1c7a3bfba61a03f1fbe79eab4d44b375450254ace147877896c7b1765f"

[[files]]
file = "shaderpacks/VECTOR_v1.3.1.zip"
hash = "037c2658a852d94801533537ef52b8434be209b4aa9102af329750c01c7350f5"

[[files]]
file = "shaderpacks/colourSplash.shaders.zip"
hash = "53c89f871a30d074ca4c8d4c207927d9bd0905bbb4a8322059426c6fd44e6dce"
