hash-format = "sha256"

[[files]]
file = "README.md"
hash = "811f4c40c6ae0437e14cf0ccf619b81aa9e51c16f141cf0ba9ace8c3c4fb019f"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "e3874989db57b0edffffac6233ecec62f54dd81984f5d0815ade9c21b07d8b90"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "f7b7309a575abc17fe84cfd9302ba80735e63dbda489deb11484f3e2192ec5ab"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "0333c9d2aaa16ea818bd61dc7ac07f13ddb99fc633d789e0460ec6f8b6b54ca0"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "322847b3a52c97fd77abcd832f173fd91655f8421b540e3c7b6071af26c4046f"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "b3db76aa8076114ce9a7b297db6961d5a1e7e03b9b142549ecc452912698d1d6"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "f6fdbc1d61acca0926cf565f02623080d913f43609713e637a4e5317702531a4"
metafile = true

[[files]]
file = "mods/auto-clicker.pw.toml"
hash = "469b081f0f5192419243d3544c59119f718720fce51aa5a43237e2821051aa11"
metafile = true

[[files]]
file = "mods/auto-lectern.pw.toml"
hash = "cc7ae2a3a4b29e1b7bbdf790b357acf67fb0e9366aa7c703b27fe39db086eae9"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f133a949fb877d6074e84766899719b1a7c0670084e5431d7e7e481397ed7f1c"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric-pr55.pw.toml"
hash = "ce8d4b10b0cdd80d466926371fa7008bb76b6a028bb16ce018e75e54ddebb8ad"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "6732aa38939e1bb23fbb759704aca4df545a77d44ab0b81244b5321d0cdfdab3"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c863f304da6fcd6c5504c1a3fe60b58b099705e922e03f039a4004f119788210"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "31100360c769ea7ca107cefa833b0bb0337fbab334103005433f2b2884214481"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "545b8f4045b6419bb276e906b611a7d679f7bd61a63c5d87723d10f24bf86e0c"
metafile = true

[[files]]
file = "mods/build-guide.pw.toml"
hash = "8c73624ce5471d6610b8fc18ee07ef3b37aebc9bae45d5d6fa41b65e1317b67f"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "03d16a42dd5672320ec4c282fe2e5a695eb4a597125b8df90e59f0aa0d89de1b"
metafile = true

[[files]]
file = "mods/cardinalboats.pw.toml"
hash = "ccced9c9ffeeddd2745d6fc920c0c0146dbf9453e0ce921b2bddbec64d7667d3"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "ab2176911e5e8c68e4de379f97376675808e6de7ec595d824d5625ede4584919"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "e54e6bb39f896ff16a97827dff5f4203d71828e4270b024180ab4c41963e4afb"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "de74b46f302c431609da6e3d9d4caff41ff6b4d81bfe4f89b96d8dc82105f916"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "dbc4d5a60092831b89c3d1b697b43324b268cb970bf01786a0edb1a7e001d87d"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "c610d021f7b69a1b79a3e550f8e7f3b9d11bdbcb0fcf9314fde7ecc7f72a26b6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "6b408e7b83e9b769fcafe9216c6f6a528d8930c6d34f7984a9e42119b5ac7d44"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "b78d967639e2a111321692ed27de64f73dbf34509fd7cc7381e1b2d440570a03"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "618f7cc1309e9cc8d129a59a0badc820e8264a5f0b3b47def75c0bfcc1668565"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "6cc4b7f79468d527048c4f1fd233d1ed82068770d4dcd4c8232493446361d14a"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "0805fa18f283ecd45f12fbccd873ace40dac22c88d210867e267873538e6c65c"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "d90952f5429e780a2cc42f6d7a90fcc2a42a5438ae85a219eade5f65a00536fb"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "38114d90c4b06d6aaa69ffc00e160c77d9fa0524c386df8ed33259ab8538aac2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "64208a61918617d47a29f6c6b3366f3769ea9815cb7d52c93ca008983d930c97"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f4f2cdfa1c6c78d3dc0df16d86bbf021d9530979d5ee5f5efdbf69ab236dfcf"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "31cae72ca49c7fc1bc9d43fb64c189a2750528ef398d6bcb95cc56dd85853bac"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3f5eab6c74f8a622faccb7be82d522ed4db2c0e45166182d76fcfe1425ea5783"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7ed8df687dc5d9229b3eabc08e8ef9c0bc3825d0f75736c53c1470adf43b4217"
metafile = true

[[files]]
file = "mods/fast-trading.pw.toml"
hash = "e326dc27562bc2b5ba50df652849c9f9ef90e7d69d23324ec8a4daddaa5cee11"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d9d10b2dc49123934063ba3454f7e703267bc812504e2c34bff5d0a16e0b4109"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "fc1bf13a39c7ae3181398ae42d1bf0927e0856e2e3a26e003118271bc1477612"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "04ac3393b4f1ca340c96ad1c3a6f7a1c0893016fde1260d6152f8b3f2956ea56"
metafile = true

[[files]]
file = "mods/gui-followers.pw.toml"
hash = "bcf66d050f9c9acb855f94a5c0f7960cd66fc5a4841d020a2f3b08ae8c18ab92"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2970741d8305951c5c14d50226f5f64e86891c14fcab17f17103710ace42aa30"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "b6c18d1fabcb89283e6ff2e68029b2296995ac62f0f091e2b2c9c75878eb452a"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "ec75f5402ea959cf3882a6d852ff00855a9103121671977de48617734423f641"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "30ddce3487c4ec89475caa20acbf065f4aff8a3f05152eb8a6b07f9f59658c48"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f4735aeddee5a11a1b17cbc8e906307e3832c26427b8acc72e1a80e54fcca9de"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "e709134428f51a0ff0a2efe1a2d039fb2ad24880753f24445e21df2b50aa313a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a66e2bd6deccaab80afcfebec417d29fd19597c6231eb475112717848a5a6f94"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "739dac878e9448237f6515a1aadb054de1751bc91d41878e2b75ee9846b9fa21"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "1cde844cbf4303c3a6f94ab7e6f23a48c5c5858357d5ebbec8ea000b1fd5602f"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "5bacac872ecef334a45f5bbe103902962863f30c84ffcb8e0c14219478082c94"
metafile = true

[[files]]
file = "mods/map-tooltip.pw.toml"
hash = "93bf5e760cb6e64e70a01b4151a920d25f18f6bca3a062d6836c11a8611743b5"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "249d8e7300c832e8ecd0b155ff38194f43463af0de0d05d3398a1a43b76d64c9"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "9d9306b91608ceaabf54fd2b88b7d8afdd11d75efe216c7f47a268ff85bb9beb"
metafile = true

[[files]]
file = "mods/music-notification.pw.toml"
hash = "9e9ba7dfdbeb2025e008661f8ecf9cc6d366365350028b2e49c2a313fd2c51c3"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "abbc4c963076179a455126378a35f5f98938492bd85cce1652d3f5634afcaec9"
metafile = true

[[files]]
file = "mods/notifmod.pw.toml"
hash = "67e1019de7c1ef06c11eb2bdcf34bd11f1a655bfa811914971b44bd1d073f30c"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "4bf4725c5be913048b3b0c6dfcdc1a98ac99baeaeda0d34dde411ab3972fb997"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "5a8266ecf742e57419d77b2ab0a55697243a7f6ea68bf61f3ec1b0e059dec7ed"
metafile = true

[[files]]
file = "mods/persistent-inventory-search.pw.toml"
hash = "3bbf890cd9be863a81f8d7f9a718205c838b55cdc84afd64663ea4a4c2346d87"
metafile = true

[[files]]
file = "mods/pocketwatch.pw.toml"
hash = "ce51eed2e9d2cab1723ef8c80717e5ae3e068e5031b6402db54b33996106d178"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "713935e70d29ff6f4afeb19a3dbe5a10602889d83cb7ce8c2ef9cbebc8f350d4"
metafile = true

[[files]]
file = "mods/ridehud.pw.toml"
hash = "578533aef08c8e14891448e8d860c56d80a8e755433041bab83e91e503d3f946"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "6128e4df310174c3a4d950fd008505fb88b3bc341af0d6b087fed90973dc02e4"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "a19fc3cd5567c145807641035153e09f45f07168f3d7850afe69407d569b0a77"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "ac79e30e827a176ea9c016275d085fe858e11ac6a72b46810124d56b151fdc41"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "ec3fde057f477624aae7e419b7c5503b9c109db8bfc05817d06d2aa093b357ea"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "81e6732a6a9d13f0a4e3aae05ab349921d2d3dc2a7af9bae66ccb8f8e39c20b2"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "7dca5b8c595020cdb89f675ec337fe85e6d8cfdd3fc1d74625a057325f224c9a"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "2d39d637f429a57ba5939a53d73f564ec56dceaf9623c2172b04f5687d1c08cd"
metafile = true

[[files]]
file = "mods/vanillaconfig.pw.toml"
hash = "8881dd65fd874b305e7c7f394ed467bc34573f2cab1068814c83425686443552"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "0bb2abb42b830e62accdca51d571db9f0455013170441ac18dc8e2a603d64e25"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "a0beeeba48f3b8cd624a1929bac6b6ecbe190318c4d848563b2982bda10953de"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6186b113e1f4b7554d2a05a04428bcdffe2fb8a1b4504d805a43ed7d035f8a6d"
metafile = true

[[files]]
file = "resourcepacks/EvenBetterEnchants_v2_r1.zip"
hash = "bf3879bfe3607936248a070037c730082a46556ef2cdfb285e05ac93a88665ea"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x.zip"
hash = "ea8ed4c8ca8266ce2e61de35f51db9effea252ba56c8681e25471c1e31c22f90"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x_BushyLeaves.zip"
hash = "36299e2ef6a16ff750e0f57ff8a27c79ca65a6200528756bfdc4d3bf835142c3"

[[files]]
file = "resourcepacks/deep-origins-overlaysÂ§8_1-2-2_1-17_1-21.zip"
hash = "17af52a6b1d484fde2b240fb3d7445bbd9dce0a7840ed1559a34fe161d592487"

[[files]]
file = "resourcepacks/no-more-map-markers.pw.toml"
hash = "78069d2844056b8508ce9abbf4d9a81bdde3e70b3f91c26b504827cc1ebff541"
metafile = true

[[files]]
file = "shaderpacks/BSL_v8.2.09.zip"
hash = "b9f9e70c83f04830007ec06e6d7c3e0fafe90c6af53355e4248ab0a59ca1cf48"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.2.1.zip"
hash = "3eeefb1c7a3bfba61a03f1fbe79eab4d44b375450254ace147877896c7b1765f"

[[files]]
file = "shaderpacks/VECTOR_v1.3.1.zip"
hash = "037c2658a852d94801533537ef52b8434be209b4aa9102af329750c01c7350f5"

[[files]]
file = "shaderpacks/colourSplash.shaders.zip"
hash = "53c89f871a30d074ca4c8d4c207927d9bd0905bbb4a8322059426c6fd44e6dce"
