hash-format = "sha256"

[[files]]
file = "README.md"
hash = "811f4c40c6ae0437e14cf0ccf619b81aa9e51c16f141cf0ba9ace8c3c4fb019f"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "e3874989db57b0edffffac6233ecec62f54dd81984f5d0815ade9c21b07d8b90"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "798cf0237f9bdd54fd81350b0d97dc92270914f05ffe7f2616163639cd209554"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "a2d0f65314163c249d4ce2e868c210f585823b701e45fc28ce12887fbc8f72a4"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "85d0ee8c777710f2f423bc5450f14471af7e6e9517750aff070c2437d08921ae"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "957d8132f7511ca2921e62e75d1176f154314d0bc87877ce2c98245d36575064"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "88a6d55d88959c47eaf2545ac1f8e212e144feaf5a2e775aef96c4f3f932ee64"
metafile = true

[[files]]
file = "mods/auto-clicker.pw.toml"
hash = "27198e06b4c129e6feb4ebce44a57b06e48fc1ff865b8ee59e5cfa6143ac0b2f"
metafile = true

[[files]]
file = "mods/auto-lectern.pw.toml"
hash = "fbc4a19bd1c36ff0ed64e0984805647f4f6cc31329d6a6c3cc996f90deefcc73"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "73c410371e865c6afd83513cc5fdc305e30221e3221a15f2bce101171207ff0c"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "283b960167f234c9f7c4bb30308eebf10e9b1007bd96ea50ae14199e829d9a15"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "802720b446f815e0b50bb44b773b0dccf465e553959337fa9582a6809b08fe05"
metafile = true

[[files]]
file = "mods/betterping.pw.toml"
hash = "59f6d32ddcccd541d950d428c4e0d8f5356754d42af13576ddc625c0b77020e4"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "32fb23526c3980e86d0920cf683baffb1c1bb9646bcba8ec296f21042780340f"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "f62aff8c5dfa82c632d4b39c3071ef8cbe686da76563f15e73a22ea229e372fc"
metafile = true

[[files]]
file = "mods/build-guide.pw.toml"
hash = "c7ce59159e3c5591ee18217ff79b555ff07f0b3152a301f05b1143dda2c4cf5b"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7e1a517b59b32c3a87e3f376e167cf84ddb23a2c894c0b70114b765b1b96bede"
metafile = true

[[files]]
file = "mods/cardinalboats.pw.toml"
hash = "5a0a07eae60c0dc8c49e2b76d0555610a3ec356f4d8a35493bd3d36b0d8fe309"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "ab2176911e5e8c68e4de379f97376675808e6de7ec595d824d5625ede4584919"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "673ae094320feca211b53709b153a2f72001b4df72f7db3e7b789300c394e62a"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "36421f2f3bd83d2a6ca069fd48dac2fc3a072aecf3ebce6787c88f3b24a17974"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "b118306ccec6ee38c87398b4f70bfceba846eb238d58903f00c67157278efbd7"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "dcddaa62838fb9d6bfc55052511cf950ec684f8ffc1073c6774738b3e43535e4"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "2ffba149ee8a8c283ec050c1ad5b5e5ef930854443f5b52fc3ef233d877a6253"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "0af7c948bfc382d1013d0341f339479e767e8d1d10e8627b6ac373ce3b5b01e3"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cc30f3ca21b6d20ce973c9f741814e9cc36f0b1a008e223814b4a984a64d5d61"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "6a4f6d4a837c51be016ea8d4d13b8fd9b786617419f7061ec996f746117b1b79"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "0805fa18f283ecd45f12fbccd873ace40dac22c88d210867e267873538e6c65c"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "4a3edb893d0fe7d1844249e4225a514fa707eade0c2e1fa51c403cfb538cb5e4"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "6dfa3b9d20833a2a754564dc3682b070d3416be893656331f79d4b6bd2a666e3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "2e92889c099e98d12c49f32f7dc4d231572aaf9ea64e0551d2cef106fe158fa8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f0ac7cd4ca7d0c647c3f4e5c8e4493fca5e21b57b94388626dcda2582b5d0fe9"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "b0a1ca637ecc9eb8bd76678f24c8305e6cd6e72d00096469dbb8764fd970325a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "03618cd9a216eb5b4897bffa083b9172c20082f3c2891c21abca7c011c08ac2c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44ce91936136fb30c08b2f062e6d92493f1f2cc5a526a8039b54d1ae3f61279c"
metafile = true

[[files]]
file = "mods/fast-trading.pw.toml"
hash = "423ad856deeea3f6c8c5d96988ef5d26ee15866fc3c6d4d06082e267a58c512e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f1da925ae791df99a453d1e135cb3c7a390c861a6ae9db299e19ffc83dfed680"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "4a831db777c19aabfe24702695f4c7c272e1e3c0f2e8fed95ef8aa79dd510ae1"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "19eec4009a0378eb02772c7e8703eab46e3f1e012f3f91f9e4662ef53951b46c"
metafile = true

[[files]]
file = "mods/gui-followers.pw.toml"
hash = "4c37b0f5ae58f5a836d2796d0737ac06d2c3480e73ab3f31ddc8fd645bac0b5f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b6ba7ce8077d6ff4b12221872fa0127ca57d5d615cde863a8169546da4b937c4"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "a1ccf31100eb4b68383f0f78fefe6fcb9001de2fb57a33478cc61f8f8f695a22"
metafile = true

[[files]]
file = "mods/infinite-trading.pw.toml"
hash = "168efdd1a9319ae74c114e99226c44ad80730432f01177a4e006e66e554095d6"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "64d079847edb5e4c7ac7752bfcc741eaca207edaa8f5d87791fc9e5d56e1a30e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "6f52f708cf28a7f5d4153bfce7842f88b0f3c4034af1b95aa2ff67f231bfee42"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "a862bf4a11ea9052e70bf24258ddc4300e25166f95757b80b10f2b9890442e2f"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "91ed92cfe978fb0f4e217b428ee12a71252e4089d996391aab4e18ca916201c6"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "fc69e351fb49f563bb86cc78ae2d693902e0bfebacc7a19916edc659eab4b325"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "f0980f4f632e35212b66e87abd9945947a9e378b54b6db0c307150c8dce3e232"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "906d9d06b00fc588b9836eb17769b19c4e94b5a729afb6f52126ef055a2a2a92"
metafile = true

[[files]]
file = "mods/map-tooltip.pw.toml"
hash = "93bf5e760cb6e64e70a01b4151a920d25f18f6bca3a062d6836c11a8611743b5"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "856cfb7576622f61349e233920315ff37aed48f96cff3fcd85182bb13d23530d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d8255eee93bf887ad02b1b81912dba40a6bfc3018dfe591d29f4a658f1292d33"
metafile = true

[[files]]
file = "mods/music-notification.pw.toml"
hash = "7336422f5a2730623d71a551fe9ebc154a89523040296639afe60ab65ade3eb1"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "e9f9b9151f3a2151660453ba14719cc713abb5d8904a9f70094f04abfd92efed"
metafile = true

[[files]]
file = "mods/notifmod.pw.toml"
hash = "67e1019de7c1ef06c11eb2bdcf34bd11f1a655bfa811914971b44bd1d073f30c"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "4bf4725c5be913048b3b0c6dfcdc1a98ac99baeaeda0d34dde411ab3972fb997"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "7bfab0c3740e4ac59f6a7d3df8d5276b54e1f7d3719c0f960c4469dbf7e67590"
metafile = true

[[files]]
file = "mods/persistent-inventory-search.pw.toml"
hash = "99f2e71922d32310759e352a492d776bc22bcdaef05fceb5ad397e72ccb9a111"
metafile = true

[[files]]
file = "mods/pocketwatch.pw.toml"
hash = "3fcd76594f2ea11f2965082a8e1b41762188f95d7e3e35682362d1f418e49c43"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "78dce7561dde35bedb64cd0bd4ae614367bd987da1b70ec90a13a83e5da0fe8b"
metafile = true

[[files]]
file = "mods/ridehud.pw.toml"
hash = "0b52e67ae5062f8da139aa7d98a9c9b4099549135d786b2905e634733122b31d"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "4b26063fca88aaa47c1bb7bce9649c2f666d915248fee6fa4e37c14a02638054"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "e96310fb44e13f5acf6b8fb8ee52345f9a90f7336d8e920590bfe8dde9476e06"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "ce1500543d903d17aff0628b1045c0d8ea42eba0a4fb743a2aefb3f3c17a7d2a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "436f18feec4972f76c70f374bc958ec5bc28b97f897b1b69a3241fbbe33821d5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d7a049ca83e2b59f08f4511f968d9aed2dc1e850b7a553fa42592815a7117224"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "aa97f22224dbf29611634ac6140e8d4c30d46ca01d7af34874aa6b36fcf3197c"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "302d02d731ac76714d31276b8bac85b042d55d8227b2a70242f5719704699e06"
metafile = true

[[files]]
file = "mods/vanillaconfig.pw.toml"
hash = "169fb09c83767afdc7cbb3ec40e27cc364077491b9192d01892e0d99575136bb"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "7d047f9e1c7e7f5bf7de5787ecd74f883c00aa5b220e2913652496d59f62afa2"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "16fcb8def7f1eb68eb62ef3e1dc396e301874dca6ff18fddc192a4458e933915"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6718ac1baa5d3107c5b45b050d86f9b6820f7d9727441e9b306a22b9a5f28cc1"
metafile = true

[[files]]
file = "resourcepacks/EvenBetterEnchants_v2_r1.zip"
hash = "bf3879bfe3607936248a070037c730082a46556ef2cdfb285e05ac93a88665ea"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x.zip"
hash = "ea8ed4c8ca8266ce2e61de35f51db9effea252ba56c8681e25471c1e31c22f90"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x_BushyLeaves.zip"
hash = "36299e2ef6a16ff750e0f57ff8a27c79ca65a6200528756bfdc4d3bf835142c3"

[[files]]
file = "resourcepacks/deep-origins-overlaysÂ§8_1-2-2_1-17_1-21.zip"
hash = "17af52a6b1d484fde2b240fb3d7445bbd9dce0a7840ed1559a34fe161d592487"

[[files]]
file = "resourcepacks/no-more-map-markers.pw.toml"
hash = "78069d2844056b8508ce9abbf4d9a81bdde3e70b3f91c26b504827cc1ebff541"
metafile = true

[[files]]
file = "shaderpacks/BSL_v8.2.09.zip"
hash = "b9f9e70c83f04830007ec06e6d7c3e0fafe90c6af53355e4248ab0a59ca1cf48"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.2.1.zip"
hash = "3eeefb1c7a3bfba61a03f1fbe79eab4d44b375450254ace147877896c7b1765f"

[[files]]
file = "shaderpacks/VECTOR_v1.3.1.zip"
hash = "037c2658a852d94801533537ef52b8434be209b4aa9102af329750c01c7350f5"

[[files]]
file = "shaderpacks/colourSplash.shaders.zip"
hash = "53c89f871a30d074ca4c8d4c207927d9bd0905bbb4a8322059426c6fd44e6dce"
