hash-format = "sha256"

[[files]]
file = "README.md"
hash = "811f4c40c6ae0437e14cf0ccf619b81aa9e51c16f141cf0ba9ace8c3c4fb019f"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "6e4a1ad878793ab3c3b7df30ea8e4177a65c3632d1b35277683d6f6b333cb073"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "633f76611e057f7dd6195a26c54fe8841e30569792e4474e9963d950fbcd17e7"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "eb586237c139da61053ce14ea9a8d6cb3124e1731db22963ae79192b59b4c063"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "0543bf0e7d7ac48e221c7e97b55ca7add1c8a1a4b9c5d487688782472fe287b9"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "417b7af3c7cb5f2681960349d3fa118733cbce5d260fadddd792abb24e52fbdc"
metafile = true

[[files]]
file = "mods/auto-clicker.pw.toml"
hash = "c482ef3873a8ade424f83cc874c01ae861c5c299359980be1f9163ccc1aa6b33"
metafile = true

[[files]]
file = "mods/auto-lectern.pw.toml"
hash = "4e9d3d6293bbc4d77eeb1959f2e30592777f2f9f3103672725526b7e47a9898f"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5b22c7bb3ecd93b5ed027aee1961da93c3ea2e723e4a9369944ca1c1a633647b"
metafile = true

[[files]]
file = "mods/beetooltip.pw.toml"
hash = "15c048f5116a6e0df27a05696945eb97b2017052c1b5d023e37ef8d98cf5a7ed"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "5309c13521cd3781aed216c44ab66f87a08eaf10d891fdce05bb7e045f59ea8c"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "0d1c2ae16cf9f53cbe868ca0c8444618d7f5ddc6ececef3db21bd27d354c263d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7c801232a6e7b3930c6c6f47f2c4cd77a539f28bc41e6d54e1710c2736d8a46f"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "9c699d5d353104ac3f42a20042b3b62f1e22c35bdd47ac3a7c1a0c89eee55b6e"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5e0adbaf5a22a684b1691eea9a8c4daa6b1eb2b5d821ac83c558ef015d15d51a"
metafile = true

[[files]]
file = "mods/brb.pw.toml"
hash = "04be795fbd9b7977281911ae0526de20340e07214562269a47ef991b1c863cd5"
metafile = true

[[files]]
file = "mods/build-guide.pw.toml"
hash = "6d948edb148223cb5e184f1a53f5a95e847e309d03407313d9ef3d4d67d7b0fe"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "1af76f25bad7ee8dad72015483d1263170707f2f17bb029557b8051b6136ff05"
metafile = true

[[files]]
file = "mods/cardinalboats.pw.toml"
hash = "e1939f69f1b60fa7e6760597acdfb4410a9ec8d9c1f21638b5ac93e30f5db766"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "73b49e93bdc437c2cd86133b5cfb0a04f80264f785ee660ce002bb24e14286c1"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "7ed2158d2715c74dc93716079c029524ffc36680358d0a79757ab1052a04af6c"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "3992f39495d3c9beb3db62f43dd45f9b383471ff4c5e274bcce146090756e672"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "8c3342aeba36b5ff34c10f0ad6c13bbeb7ea4f040683aba80e83776697ceda0d"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
hash = "6a601bbfca4b6310c602cedb7a49a198604dda6d516bcf587622495f5be23421"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d345d14d9672063419184ece254b77a51386160916058bb24a4af7faabc88d99"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "66de4887711dd677ddf73c852857f7a3c5cb26c4eccec0e0fba2f79ff3a725aa"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "0f24f7bd2057b70b6816de4e66922b64f8b6635dc603e40cc45d62646dc7221d"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "0cc365d0b8dc524a0b857c8bd162a478b1f52e5a307f18b32ef8c8091ad29259"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "97ca0b01ac6888486402018e7c95ec3b219a89c3338a416fd25418def5f51fa1"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "bcd6ab63410cedbf87e7056337ddf50059655c59a23189520a22eab8419b8415"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "616c7ca64b9f4af3f5283eaae4cb0be10cff8059e8db9c4e7d7b4422474aa8b1"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "471ae9c39007497d4c1d3f3f1a85334593ca9fdfb6521093e6faa2c01b74f624"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "9099b858e94f6f81db890c7d46f85601dee71ba33fb7ae19773b8da2ce8c3834"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f1cfb6d5b1aeae9d349d909fc3170f60332b6347493543a2e4f1f0801f4a5d4d"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "83659a3a4453eecd4d98ba2f7fc52070bcd2ab0d1b31d0cfd2f34bd1baa469e1"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9e796b52f72bd9eee7d716a5014d8214956ed3f7661d0f44af85c8a86775bbbf"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "078c828454d8a361baae372b5ee3dc33e5f3573fa19bdac8589b38da9dbc5c03"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "dc4ef22845aeb2681098eab37f3ca33138287ed3618b3499bc111a456f41eae8"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "26466dd3f9aaaaf89f5090f3486ed371f9d7bf7762f385584ad8cc5bf272308f"
metafile = true

[[files]]
file = "mods/gui-followers.pw.toml"
hash = "5faee0ee6e0e0c39dc4b2c7660ad478790ccf6a07726b50fe3eec4c73ac501eb"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "29b7078e678c6b90f607f9b09eaedc927fb274382963f39138b72243f2714224"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "49e7fd585c233da81e0825d1679028c7e0bc1eb74dafa98f25cab88437f53ed1"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ec7ddc7195eaec44adb0a060c48d919bedb82775a3b683f8da21ab2eb6921ab1"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "69d66eb2faaa6c9d4ca90715c729a25af6df137ce0a12133b6476b8215de7bbf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "315648c1b6910b274d4a16bda8eba7ddf380d928edb20c0c36f3ff9776e30fe5"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "e97ccca4e7d91245653fb75026534cbcd4868cbd0614e08dd94d7a82e410dbd3"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4ee72fa3b6d91ccec6ec3420396db368dc5097350ee2bb909af3a65f0446c9d5"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "102f7e8d7490e1ed36c25db3f1af7d51483806f57f856c2aeb03686594a10417"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "b192197125a087db65cb0dbac80fe89db6b6eb6b5b3129e1ffe11fdfeab82216"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "f66be8e2a4bde1ddac585cc7dfb4b9b16a3babb095b4f9f130ae7ecebac5c2cb"
metafile = true

[[files]]
file = "mods/map-tooltip.pw.toml"
hash = "7903d3643dbbb226096f732adc21013e24f7fddf205e1163c47df1705e1cefa2"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "51d318e0a4bc5da935a965860b815a6cb57b6ef0ff046a1c364996ca784b1582"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e37792db4c4b69e11243c7470f0f2a791dc016381e460cd5616eccb6b567b5ab"
metafile = true

[[files]]
file = "mods/music-notification.pw.toml"
hash = "f0db0eea555958035a37acb5c4bdca60f1d9729ad7b6dfd0ae7c4aa991c1c9e1"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "8221d0376bdd5c13684d44ce2dcfc994f4aeea8d21546b9a562e71517ba1ce80"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "25d0816132441ac49e4711c5f701bf10b12207cb0895d0c06c5f639da158b9bd"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "2205e3bc9e060ed011eb6252b27973d8184b7d54d8240cb92baf7196f3bf7eab"
metafile = true

[[files]]
file = "mods/persistent-inventory-search.pw.toml"
hash = "43e85d8b8951503570e29e6540b57c0feb117bdb6d2968952c2cf4071cb76a09"
metafile = true

[[files]]
file = "mods/pocketwatch.pw.toml"
hash = "7dcb07c8d65381799722375e82a95bdf0da98c50b6842aa36ca67c68138f47ff"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c497424b603b0b9fc190427fd7aa0985d23a74f4cba6c554e14f7dbd29385df2"
metafile = true

[[files]]
file = "mods/ridehud.pw.toml"
hash = "073ca97763698db43e4a1cd40f332a4b5c8a1029191b69775a95a325c91b163b"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "f632c6f98de8644ad2fa0153ab1211bd9f2751fe84620b894ab5f6f558efaae4"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "45910a70021a8db0da310c1255a255402b052d53c944ecb9159d29e7c0e6db45"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "79ec58c99084d5b02044e04b6860bc6339868e95e1a8c7a982f5400ee777b178"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "28f2167da063c1be7b1f4e534cdcbb446daa569cc32ffe1c0705663a9a06a5b9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "280cf7ad4ec95bd95eef81a7f327095c5f40e1b8aa45cea91284bfd19395d69e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "afc06fed4e996bf3ad5cf2e8248d1cfc6650d8cae19fc8c6745e41c085c8eb2d"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "6533e7eaad68cad764272e5c4857a075ceb8a149546fec0d16179ba2a1a49fee"
metafile = true

[[files]]
file = "mods/vanillaconfig.pw.toml"
hash = "97f02d1e437693a8135cc701df1447d6ab74d893bc12315e10d79f2dac0d47cd"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "6cb2a4cd4eb40eaf19bbb54a6d8fa23643470147e86e19fe04b820e170998ed3"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "3f93201b4be0f7eea0294e1acab273f25c3c4c399711c00376baed38cacb762c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "7f7768f2047011ed61c9bbec29bbcd2d06c5eb8ab731d442b9ecc2c01bbc8c6b"
metafile = true

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x.zip"
hash = "ea8ed4c8ca8266ce2e61de35f51db9effea252ba56c8681e25471c1e31c22f90"

[[files]]
file = "resourcepacks/VanillaTweaks_MC1.21.x_BushyLeaves.zip"
hash = "36299e2ef6a16ff750e0f57ff8a27c79ca65a6200528756bfdc4d3bf835142c3"

[[files]]
file = "resourcepacks/deep-origins-overlaysÂ§8_1-2-2_1-17_1-21.zip"
hash = "17af52a6b1d484fde2b240fb3d7445bbd9dce0a7840ed1559a34fe161d592487"

[[files]]
file = "shaderpacks/BSL_v8.2.09.zip"
hash = "b9f9e70c83f04830007ec06e6d7c3e0fafe90c6af53355e4248ab0a59ca1cf48"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.2.1.zip"
hash = "3eeefb1c7a3bfba61a03f1fbe79eab4d44b375450254ace147877896c7b1765f"

[[files]]
file = "shaderpacks/VECTOR_v1.3.1.zip"
hash = "037c2658a852d94801533537ef52b8434be209b4aa9102af329750c01c7350f5"

[[files]]
file = "shaderpacks/colourSplash.shaders.zip"
hash = "53c89f871a30d074ca4c8d4c207927d9bd0905bbb4a8322059426c6fd44e6dce"
