name = "VanillaPlus"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03d607ebe63aba1bb1d16d196962a16902ea8c0ba07716d05b0bacaf768d3ebc"

[versions]
fabric = "0.16.14"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21.1"]
