name = "VanillaPlus"
author = "Thecat8413"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dcc3fa592d8fb6b6c7b07c4ac5311ebd6794e8e9097b6809ec9f909ebc3b2da"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
